server:
  port: 80

  datasource:
    druid:
      url: jdbc:mysql://119.3.186.94:3306/aperture-acl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&SSL=false
      username: root
      password: Halo_xiao@123

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

spring:
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}





