server:
  port: 7000
spring:
  application:
    name: aperture-acl

  datasource:
    druid:
      url: jdbc:mysql://119.3.186.94:3306/aperture-acl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&SSL=false
      username: root
      password: Halo_xiao@123

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

