server:
  port: 7000
spring:
  application:
    name: aperture-acl

  datasource:
    druid:
      url: jdbc:mysql://119.3.186.94:3306/aperture-acl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&SSL=false
      username: root
      password: Halo_xiao@123


  cloud:
    nacos:
      discovery:
        server-addr: 49.234.83.167:8848
        service:
      config:
        server-addr: 49.234.83.167:8848


mybatis-plus.mapper-locations: classpath:com/aperture/community/acl/mapper/xml/*.xml

