server:
  port: 9001

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aperture-member?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 49.234.83.167:8848
    sentinel:
      transport:
        dashboard: 49.234.83.167:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 49.234.83.167:8848
  #            dataId:
#            groupId
#            data-type: json
#            rule-type: flow

#    alibaba:
#      seata:
#        tx-service-group:

  redis:
    host: 192.168.200.128

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.aperture.community.member: debug
    io:
      seata: info

rocketmq:
  name-server: 49.234.83.167:9876
  producer:
    group: memberGroup
mq:
  topic: memberTopic
  member:
    tag: memberTag

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true # 激活sentinel对feign的支持

